version: "3.9"
services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: ilotti_db
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-test}
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7.2.4-alpine3.19
    container_name: ilotti_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: always
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ilotti_app
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-test}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      SECRET_TOKEN: ${SECRET_TOKEN}
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

volumes:
  db_data:
  redis_data: